### ISSUE TITLE
Complete extension support for PostgreSQL 17

### ISSUE THREAD

**Issue by Vonng** [Vonng/pigsty#459]
While Pigsty has support for PostgreSQL 17, lots of extensions are still missing for that major version. Thus, we have to build these extensions for PG17.

## RPM

The [pgsql-rpm](https://github.com/pgsty/pgsql-rpm) project is working on it.

- [x] plv8 3.2.3
- [x] supautils 2.4.0
- [x] icu_ext 1.9.0
- [x] redis_fdw 17
- [x] pg_failover_slots 1.1.0
- [x] agg_for_vecs 1.3.0 with pg16 / 17
- [x] unit 7.7 -> 7.9 (obsolete)
- [x] pg_uri 16 17
- [x] pg_mon 16
- [x] quantile 16 17
- [x] lower_quantile 16 17
- [x] pg_protobuf 16 17
- [x] log_fdw 1.4 pg17
- [x] pg_duckdb to the latest commit
- [x] pgmq 1.4.4
- [x] pg_timeseries 0.1.6 (new)
- [x] pg_idkit 0.2.4
- [x] pg_graphql 1.5.9
- [x] pg_jsonschema 0.3.2
- [x] pgvectorscale 0.3.0
- [x] pgsmcrypto (+17)
- [x] pg_tiktoken (+17)
- [x] wrappers 0.4.2 (pgrx 0.11.3)
- [x] pg_later 0.1.3 (pgrx 0.11.3)
- [x] pg_vectorize 0.18.3 (pgrx 0.11.3)
- [x] plprql 1.0.0 (pgrx 0.11.3)
- [x] pg_vectorize 0.18.3 (pgrx 0.11.3)
- [x] pg_later 0.1.3 (pgrx 0.11.3)

**TODO**:

- [ ] wrappers 0.4.3 with PG 17 support
- [ ] pg_graphql official release
- [ ] pg_jsonschema official release
- [ ] plprql with PG 17 support
- [ ] pg_vectorize & pg_later with PG 17 support 

------

## Deb

Not begain yet

**Comment by Vonng** [comment]
resolved in v3.0.4
